import { RankingQuarter, RankingRequirement, RankingRequirementSeed } from '../types';

export const RANKING_SEED_VERSION = 3;

export const buildDefaultRankingQuarters = (year: number): RankingQuarter[] => ([
  {
    id: `ranking_q1_${year}`,
    name: '1º Trimestre',
    number: 1,
    year,
    status: 'ACTIVE',
    startsAt: `${year}-03-01`,
    endsAt: `${year}-05-31`,
    ativo: true,
    ordem: 1,
    origem: 'PADRAO'
  },
  {
    id: `ranking_q2_${year}`,
    name: '2º Trimestre',
    number: 2,
    year,
    status: 'CLOSED',
    startsAt: `${year}-06-01`,
    endsAt: `${year}-08-31`,
    ativo: true,
    ordem: 2,
    origem: 'PADRAO'
  },
  {
    id: `ranking_q3_${year}`,
    name: '3º Trimestre',
    number: 3,
    year,
    status: 'ARCHIVED',
    startsAt: `${year}-09-01`,
    endsAt: `${year}-11-30`,
    ativo: true,
    ordem: 3,
    origem: 'PADRAO'
  }
]);

export const rankingRequirementsQuarter1Seed: RankingRequirementSeed[] = [
  {
    id: 'q1-planejamento-unidade',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Planejamento da Unidade',
    description:
      'Entregar o planejamento anual até a data definida pela diretoria, contendo metas espirituais, sociais e operacionais.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 1,
    active: true
  },
  {
    id: 'q1-unidade-completa',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Unidade completa',
    description:
      'Cada unidade deverá ser composta por 01 Conselheiro(a), 01 Adjunto(a) de Conselheiro(a) e 04 Desbravadores(as) com idade entre 10 e 15 anos. Unidade com todos os cargos e membros definidos e ativos até o final do trimestre.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de desbravadores novos na unidade',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'PER_UNIT',
    bonusValue: 100,
    bonusDescription: 'Bônus de +100 pontos para cada desbravador novo na unidade.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 2,
    active: true
  },
  {
    id: 'q1-livro-atas-atos-patrimonio-cota',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Livro de Atas, Atos, Patrimônio e Cota da Unidade',
    description:
      'Livro devidamente organizado, atualizado e pronto para conferência.',
    points: 200,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 3,
    active: true
  },
  {
    id: 'q1-inscricao-clube',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Realizar inscrição do Clube',
    description:
      'Unidade completa em que todos pagaram a inscrição do Clube no valor de R$ 30,00.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 60,
    penaltyDescription: 'Perda de 60 pontos caso não estejam todos em dia.',
    maxManualScore: null,
    displayOrder: 4,
    active: true
  },
  {
    id: 'q1-reunioes-mensais-unidade',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Reuniões mensais da unidade',
    description:
      'Realizar reuniões mensais da unidade e informar dia e horário à diretoria. Cantinho de unidade não conta como reunião.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 5,
    active: true
  },
  {
    id: 'q1-visita-desbravadores',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Visita aos Desbravadores',
    description:
      'Realizar 01 visita por trimestre a cada desbravador, utilizando a ficha de visitação.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 60,
    penaltyDescription: 'Perda de 60 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 6,
    active: true
  },
  {
    id: 'q1-insignia-excelencia',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Insígnia de Excelência',
    description:
      'Desbravadores de 10 a 15 anos que manterem boa conduta na igreja, casa, escola, clube e em qualquer lugar estarão aptos a receber a insígnia de excelência entregue ao final do ano.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 100,
    penaltyDescription:
      'Perda de 100 pontos se na unidade não tiver nenhum desbravador apto a receber a insígnia.',
    maxManualScore: null,
    displayOrder: 7,
    active: true
  },
  {
    id: 'q1-frequencia-conselheiros',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Frequência dos conselheiros',
    description: 'Estar presente em todas as reuniões de conselheiros.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 100,
    penaltyDescription: 'Perda de 100 pontos por não comparecimento.',
    maxManualScore: null,
    displayOrder: 8,
    active: true
  },
  {
    id: 'q1-devocional-pessoal',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Devocional Pessoal',
    description:
      'Todos os desbravadores devem realizar leitura da Bíblia e estudo da lição semanal da Escola Sabatina.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: true,
    quantityLabel:
      'Quantidade de desbravadores não batizados presentes na Escola Sabatina',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'PER_UNIT',
    bonusValue: 50,
    bonusDescription:
      'Bônus de +50 pontos por desbravador não batizado presente na Escola Sabatina.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 9,
    active: true
  },
  {
    id: 'q1-frequencia-cultos',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Frequência aos Cultos',
    description: 'Participação da unidade nos cultos da igreja.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 10,
    active: true
  },
  {
    id: 'q1-frequencia-reunioes-clube',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Frequência às Reuniões do Clube',
    description: 'Participação nas reuniões e atividades do clube.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 11,
    active: true
  },
  {
    id: 'q1-semana-santa',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Semana Santa',
    description: 'Participação nas programações da Semana Santa.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 12,
    active: true
  },
  {
    id: 'q1-frequentar-pg',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Frequentar um PG',
    description: 'Participação da unidade em Pequeno Grupo.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 13,
    active: true
  },
  {
    id: 'q1-classes',
    quarterNumber: 1,
    category: 'Desenvolvimento do Desbravador',
    name: 'Classes',
    description:
      'Todos os desbravadores deverão estar participando ativamente de sua Classe de acordo com a sua idade.',
    points: 200,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 14,
    active: true
  },
  {
    id: 'q1-nos-amarras',
    quarterNumber: 1,
    category: 'Desenvolvimento do Desbravador',
    name: 'Nós e Amarras',
    description:
      'A cada reunião em que se pedir os nós, a unidade receberá 10 pontos se alcançar sucesso na realização dos nós.',
    points: 10,
    ruleType: 'RECURRING',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de reuniões com êxito em nós e amarras',
    pointsPerUnit: 10,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 15,
    active: true
  },
  {
    id: 'q1-provao-ubn',
    quarterNumber: 1,
    category: 'Desenvolvimento do Desbravador',
    name: 'Provão de UBN',
    description: 'Participação na prova na data definida pelo Clube.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription:
      'Bônus de +50 pontos para a unidade que obtiver maior pontuação.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 16,
    active: true
  },
  {
    id: 'q1-atividades-lucrativas',
    quarterNumber: 1,
    category: 'Finanças',
    name: 'Participar das atividades lucrativas do clube',
    description:
      'Participar das sociais e atividades propostas pelo clube para arrecadação de fundos monetários.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 150,
    penaltyDescription: 'Perda de 150 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 17,
    active: true
  },
  {
    id: 'q1-vendas-unidade',
    quarterNumber: 1,
    category: 'Finanças',
    name: 'Vendas na unidade',
    description:
      'Cada unidade deverá ter pelo menos uma venda durante o ano, para comprar as coisas da unidade.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 200,
    penaltyDescription: 'Perda de 200 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 18,
    active: true
  },
  {
    id: 'q1-socio-desbravador',
    quarterNumber: 1,
    category: 'Finanças',
    name: 'Sócio Desbravador',
    description:
      'Meta de 04 sócios por unidade assíduos durante o ano. 100 pontos por cada sócio conquistado.',
    points: 400,
    ruleType: 'QUANTITY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de sócios conquistados',
    pointsPerUnit: 100,
    maxQuantity: 4,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 19,
    active: true
  }
];

export const DEPRECATED_SEED_IDS_V2_TO_V3 = [
  'req_acao_missionaria',
  'req_reuniao_fora',
  'req_culto_presenca',
  'req_avaliacao_manual'
];

export const rankingRequirementsQuarter2Seed: RankingRequirementSeed[] = [
  // --- Evangelismo ---
  {
    id: 'q2-classe-biblica',
    quarterNumber: 2,
    category: 'Evangelismo',
    name: 'Classe Bíblica',
    description: 'Todos os desbravadores não batizados devem estar frequentando a Classe Bíblica.',
    points: 300,
    ruleType: 'BOOLEAN',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 1, active: true
  },
  {
    id: 'q2-capelania',
    quarterNumber: 2,
    category: 'Evangelismo',
    name: 'Capelania',
    description: 'Realizar capelania no clube com organização e participação.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: true, bonusType: 'FIXED', bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos para a capelania mais criativa.',
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 2, active: true
  },
  {
    id: 'q2-ano-biblico',
    quarterNumber: 2,
    category: 'Evangelismo',
    name: 'Ano Bíblico',
    description: 'Todo desbravador receberá Bíblia personalizada com calendário do Ano Bíblico. Avaliação por participação nas atividades bíblicas propostas, incluindo Kahoot nas capelanias.',
    points: 400,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: true, bonusType: 'FIXED', bonusValue: 20,
    bonusDescription: 'Bônus de +20 pontos para a unidade vencedora do concurso bíblico em cada capelania.',
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 3, active: true
  },
  // --- Vida Espiritual e Igreja ---
  {
    id: 'q2-impacto-esperanca',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Impacto Esperança',
    description: 'Participação nas ações do Impacto Esperança.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: true, bonusType: 'FIXED', bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 100% da unidade presente.',
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 4, active: true
  },
  {
    id: 'q2-dons-talentos',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Dons e Talentos',
    description: 'Todos os conselheiros deverão estar ajudando em outros departamentos da igreja, além do Clube de Desbravadores.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: true, penaltyType: 'FIXED', penaltyValue: 100,
    penaltyDescription: 'Perda de 100 pontos caso não cumpra.',
    maxManualScore: null, displayOrder: 5, active: true
  },
  {
    id: 'q2-quebrando-silencio',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Quebrando o Silêncio',
    description: 'Participação na campanha Quebrando o Silêncio.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: true, bonusType: 'FIXED', bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 100% da unidade presente.',
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 6, active: true
  },
  {
    id: 'q2-unidade-igreja',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Unidade/Igreja',
    description: 'Realizar 01 Escola Sabatina e 01 Culto JA conduzidos pela unidade.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 7, active: true
  },
  {
    id: 'q2-jejum',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Jejum',
    description: 'Participação mínima de 50% da unidade no jejum.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 8, active: true
  },
  {
    id: 'q2-desafio-memoria',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Desafio da Memória',
    description: 'Um desbravador por unidade recita o desafio mensal.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 9, active: true
  },
  // --- Família ---
  {
    id: 'q2-pais-presentes',
    quarterNumber: 2,
    category: 'Família',
    name: 'Pais Presentes',
    description: 'Levar pais para eventos do clube ou da unidade.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 10, active: true
  },
  {
    id: 'q2-reunioes-pais',
    quarterNumber: 2,
    category: 'Família',
    name: 'Reuniões de Pais',
    description: '80% de presença dos pais nas reuniões convocadas.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 11, active: true
  },
  // --- Desenvolvimento do Desbravador ---
  {
    id: 'q2-nos-amarras',
    quarterNumber: 2,
    category: 'Desenvolvimento do Desbravador',
    name: 'Nós e Amarras',
    description: 'A cada reunião em que se pedir os nós, a unidade receberá 10 pontos se alcançar sucesso na execução dos nós.',
    points: 10,
    ruleType: 'RECURRING',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de reuniões com êxito em nós e amarras',
    pointsPerUnit: 10,
    maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: false, penaltyType: null, penaltyValue: null, penaltyDescription: null,
    maxManualScore: null, displayOrder: 12, active: true
  },
  // --- Finanças ---
  {
    id: 'q2-socio-desbravador',
    quarterNumber: 2,
    category: 'Finanças',
    name: 'Sócio Desbravador',
    description: 'Meta de 04 sócios por unidade assíduos durante o ano. 100 pontos por cada sócio conquistado. O sócio pode ser pais/responsáveis, membros da igreja ou amigos externos.',
    points: 400,
    ruleType: 'QUANTITY_WITH_PENALTY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de sócios conquistados',
    pointsPerUnit: 100,
    maxQuantity: 4,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: true, penaltyType: 'MANUAL', penaltyValue: null,
    penaltyDescription: 'Perda de 100 pontos a cada sócio desistente ou 400 pontos caso não consiga nenhum sócio.',
    maxManualScore: null, displayOrder: 13, active: true
  },
  {
    id: 'q2-vendas-unidade',
    quarterNumber: 2,
    category: 'Finanças',
    name: 'Vendas na Unidade',
    description: 'Cada unidade deverá ter pelo menos uma venda durante o ano para comprar itens da unidade.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false, quantityLabel: null, pointsPerUnit: null, maxQuantity: null,
    allowBonus: false, bonusType: null, bonusValue: null, bonusDescription: null,
    allowPenalty: true, penaltyType: 'FIXED', penaltyValue: 200,
    penaltyDescription: 'Perda de 200 pontos caso não cumpra.',
    maxManualScore: null, displayOrder: 14, active: true
  }
];

export const DEFAULT_RANKING_REQUIREMENT_SEEDS: RankingRequirementSeed[] = [
  ...rankingRequirementsQuarter1Seed,
  ...rankingRequirementsQuarter2Seed
];

export const buildDefaultRankingRequirements = (year: number): RankingRequirement[] => {
  const quarters = buildDefaultRankingQuarters(year);
  const quarterMap = new Map(quarters.map(quarter => [quarter.number, quarter.id]));

  return DEFAULT_RANKING_REQUIREMENT_SEEDS.map(seed => ({
    ...seed,
    quarterId: quarterMap.get(seed.quarterNumber) || '',
    active: seed.active,
    origem: 'PADRAO' as const
  }));
};
