import { RankingQuarter, RankingRequirement, RankingRequirementSeed } from '../types';

export const RANKING_SEED_VERSION = 2;

const quarterRanges: Array<{ number: number; month: number; day: number; endMonth: number; endDay: number }> = [
  { number: 1, month: 3, day: 1, endMonth: 5, endDay: 31 },
  { number: 2, month: 6, day: 1, endMonth: 8, endDay: 31 },
  { number: 3, month: 9, day: 1, endMonth: 11, endDay: 30 },
];

const detectActiveQuarterNumber = (year: number): number => {
  const today = new Date();
  if (today.getFullYear() !== year) return 1;
  for (const q of quarterRanges) {
    const start = new Date(year, q.month - 1, q.day);
    const end = new Date(year, q.endMonth - 1, q.endDay, 23, 59, 59);
    if (today >= start && today <= end) return q.number;
  }
  return 1;
};

export const buildDefaultRankingQuarters = (year: number): RankingQuarter[] => {
  const activeNum = detectActiveQuarterNumber(year);
  return [
    {
      id: `ranking_q1_${year}`,
      name: '1º Trimestre',
      number: 1,
      year,
      status: activeNum === 1 ? 'ACTIVE' : 'CLOSED',
      startsAt: `${year}-03-01`,
      endsAt: `${year}-05-31`,
      ativo: true,
      ordem: 1,
      origem: 'PADRAO'
    },
    {
      id: `ranking_q2_${year}`,
      name: '2º Trimestre',
      number: 2,
      year,
      status: activeNum === 2 ? 'ACTIVE' : activeNum < 2 ? 'CLOSED' : 'CLOSED',
      startsAt: `${year}-06-01`,
      endsAt: `${year}-08-31`,
      ativo: true,
      ordem: 2,
      origem: 'PADRAO'
    },
    {
      id: `ranking_q3_${year}`,
      name: '3º Trimestre',
      number: 3,
      year,
      status: activeNum === 3 ? 'ACTIVE' : 'CLOSED',
      startsAt: `${year}-09-01`,
      endsAt: `${year}-11-30`,
      ativo: true,
      ordem: 3,
      origem: 'PADRAO'
    }
  ];
};

export const rankingRequirementsQuarter1Seed: RankingRequirementSeed[] = [
  {
    id: 'q1-planejamento-unidade',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Planejamento da Unidade',
    description:
      'Entregar o planejamento anual até a data definida pela diretoria, contendo metas espirituais, sociais e operacionais.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 1,
    active: true
  },
  {
    id: 'q1-unidade-completa',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Unidade completa',
    description:
      'Cada unidade deverá ser composta por 01 Conselheiro(a), 01 Adjunto(a) de Conselheiro(a) e 04 Desbravadores(as) com idade entre 10 e 15 anos. Unidade com todos os cargos e membros definidos e ativos até o final do trimestre.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de desbravadores novos na unidade',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'PER_UNIT',
    bonusValue: 100,
    bonusDescription: 'Bônus de +100 pontos para cada desbravador novo na unidade.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 2,
    active: true
  },
  {
    id: 'q1-livro-atas-atos-patrimonio-cota',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Livro de Atas, Atos, Patrimônio e Cota da Unidade',
    description:
      'Livro devidamente organizado, atualizado e pronto para conferência.',
    points: 200,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 3,
    active: true
  },
  {
    id: 'q1-inscricao-clube',
    quarterNumber: 1,
    category: 'Secretaria e Organização',
    name: 'Realizar inscrição do Clube',
    description:
      'Unidade completa em que todos pagaram a inscrição do Clube no valor de R$ 30,00.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 60,
    penaltyDescription: 'Perda de 60 pontos caso não estejam todos em dia.',
    maxManualScore: null,
    displayOrder: 4,
    active: true
  },
  {
    id: 'q1-reunioes-mensais-unidade',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Reuniões mensais da unidade',
    description:
      'Realizar reuniões mensais da unidade e informar dia e horário à diretoria. Cantinho de unidade não conta como reunião.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 5,
    active: true
  },
  {
    id: 'q1-visita-desbravadores',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Visita aos Desbravadores',
    description:
      'Realizar 01 visita por trimestre a cada desbravador, utilizando a ficha de visitação.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 60,
    penaltyDescription: 'Perda de 60 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 6,
    active: true
  },
  {
    id: 'q1-insignia-excelencia',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Insígnia de Excelência',
    description:
      'Desbravadores de 10 a 15 anos que manterem boa conduta na igreja, casa, escola, clube e em qualquer lugar estarão aptos a receber a insígnia de excelência entregue ao final do ano.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 100,
    penaltyDescription:
      'Perda de 100 pontos se na unidade não tiver nenhum desbravador apto a receber a insígnia.',
    maxManualScore: null,
    displayOrder: 7,
    active: true
  },
  {
    id: 'q1-frequencia-conselheiros',
    quarterNumber: 1,
    category: 'Vida da Unidade',
    name: 'Frequência dos conselheiros',
    description: 'Estar presente em todas as reuniões de conselheiros.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 100,
    penaltyDescription: 'Perda de 100 pontos por não comparecimento.',
    maxManualScore: null,
    displayOrder: 8,
    active: true
  },
  {
    id: 'q1-devocional-pessoal',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Devocional Pessoal',
    description:
      'Todos os desbravadores devem realizar leitura da Bíblia e estudo da lição semanal da Escola Sabatina.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: true,
    quantityLabel:
      'Quantidade de desbravadores não batizados presentes na Escola Sabatina',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'PER_UNIT',
    bonusValue: 50,
    bonusDescription:
      'Bônus de +50 pontos por desbravador não batizado presente na Escola Sabatina.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 9,
    active: true
  },
  {
    id: 'q1-frequencia-cultos',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Frequência aos Cultos',
    description: 'Participação da unidade nos cultos da igreja.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 10,
    active: true
  },
  {
    id: 'q1-frequencia-reunioes-clube',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Frequência às Reuniões do Clube',
    description: 'Participação nas reuniões e atividades do clube.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 11,
    active: true
  },
  {
    id: 'q1-semana-santa',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Semana Santa',
    description: 'Participação nas programações da Semana Santa.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 12,
    active: true
  },
  {
    id: 'q1-frequentar-pg',
    quarterNumber: 1,
    category: 'Vida Espiritual Inicial',
    name: 'Frequentar um PG',
    description: 'Participação da unidade em Pequeno Grupo.',
    points: 60,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: 'Bônus de +50 pontos com 85% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 13,
    active: true
  },
  {
    id: 'q1-classes',
    quarterNumber: 1,
    category: 'Desenvolvimento do Desbravador',
    name: 'Classes',
    description:
      'Todos os desbravadores deverão estar participando ativamente de sua Classe de acordo com a sua idade.',
    points: 200,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 14,
    active: true
  },
  {
    id: 'q1-nos-amarras',
    quarterNumber: 1,
    category: 'Desenvolvimento do Desbravador',
    name: 'Nós e Amarras',
    description:
      'A cada reunião em que se pedir os nós, a unidade receberá 10 pontos se alcançar sucesso na realização dos nós.',
    points: 10,
    ruleType: 'RECURRING',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de reuniões com êxito em nós e amarras',
    pointsPerUnit: 10,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 15,
    active: true
  },
  {
    id: 'q1-provao-ubn',
    quarterNumber: 1,
    category: 'Desenvolvimento do Desbravador',
    name: 'Provão de UBN',
    description: 'Participação na prova na data definida pelo Clube.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription:
      'Bônus de +50 pontos para a unidade que obtiver maior pontuação.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 16,
    active: true
  },
  {
    id: 'q1-atividades-lucrativas',
    quarterNumber: 1,
    category: 'Finanças',
    name: 'Participar das atividades lucrativas do clube',
    description:
      'Participar das sociais e atividades propostas pelo clube para arrecadação de fundos monetários.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 150,
    penaltyDescription: 'Perda de 150 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 17,
    active: true
  },
  {
    id: 'q1-vendas-unidade',
    quarterNumber: 1,
    category: 'Finanças',
    name: 'Vendas na unidade',
    description:
      'Cada unidade deverá ter pelo menos uma venda durante o ano, para comprar as coisas da unidade.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 200,
    penaltyDescription: 'Perda de 200 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 18,
    active: true
  },
  {
    id: 'q1-socio-desbravador',
    quarterNumber: 1,
    category: 'Finanças',
    name: 'Sócio Desbravador',
    description:
      'Meta de 04 sócios por unidade assíduos durante o ano. 100 pontos por cada sócio conquistado.',
    points: 400,
    ruleType: 'QUANTITY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de sócios conquistados',
    pointsPerUnit: 100,
    maxQuantity: 4,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 19,
    active: true
  }
];

export const rankingRequirementsQuarter2Seed: RankingRequirementSeed[] = [
  {
    id: 'q2-classe-biblica',
    quarterNumber: 2,
    category: 'Evangelismo',
    name: 'Classe Bíblica',
    description: 'Todos os desbravadores não batizados devem estar frequentando a Classe Bíblica.',
    points: 300,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 1,
    active: true
  },
  {
    id: 'q2-capelania',
    quarterNumber: 2,
    category: 'Evangelismo',
    name: 'Capelania',
    description: 'Realizar capelania no clube com organização e participação. A capelania mais criativa recebe +50 pontos. Se houver mais de uma capelania com distinção, o bônus é acumulativo (quantidade de capelanias mais criativas × 50).',
    points: 200,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de capelanias com distinção de mais criativa',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'PER_UNIT',
    bonusValue: 50,
    bonusDescription: '+50 pontos por cada capelania em que a unidade foi eleita a mais criativa.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 2,
    active: true
  },
  {
    id: 'q2-ano-biblico',
    quarterNumber: 2,
    category: 'Evangelismo',
    name: 'Ano Bíblico',
    description:
      'Todo Desbravador irá receber uma Bíblia personalizada com o calendário do Ano Bíblico. Será avaliada a participação nas atividades bíblicas propostas, incluindo Kahoot nas Capelanias (concurso bíblico). A unidade vencedora do Kahoot/concurso bíblico recebe +20 pontos a cada capelania. Pontuação total = 400 + (quantidade de capelanias vencidas × 20).',
    points: 400,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de capelanias vencidas no Kahoot/concurso bíblico',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'PER_UNIT',
    bonusValue: 20,
    bonusDescription: '+20 pontos por cada capelania em que a unidade venceu o Kahoot/concurso bíblico.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 3,
    active: true
  },
  {
    id: 'q2-impacto-esperanca',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Impacto Esperança',
    description: 'Participação nas ações do Impacto Esperança.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: '+50 pontos com 100% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 4,
    active: true
  },
  {
    id: 'q2-dons-talentos',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Dons e Talentos',
    description:
      'Todos os conselheiros deverão estar ajudando em outros departamentos da igreja, além do Clube de Desbravadores.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 100,
    penaltyDescription: 'Perda de 100 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 5,
    active: true
  },
  {
    id: 'q2-quebrando-silencio',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Quebrando o Silêncio',
    description: 'Participação na campanha Quebrando o Silêncio.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription: '+50 pontos com 100% da unidade presente.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 6,
    active: true
  },
  {
    id: 'q2-unidade-igreja',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Unidade/Igreja',
    description: 'Realizar 01 Escola Sabatina e 01 JA conduzidos pela unidade.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 7,
    active: true
  },
  {
    id: 'q2-jejum',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Jejum',
    description: 'Participação mínima de 50% da unidade no jejum.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 8,
    active: true
  },
  {
    id: 'q2-desafio-memoria',
    quarterNumber: 2,
    category: 'Vida Espiritual e Igreja',
    name: 'Desafio da Memória',
    description: 'Um desbravador por unidade recita o desafio mensal.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 9,
    active: true
  },
  {
    id: 'q2-pais-presentes',
    quarterNumber: 2,
    category: 'Família',
    name: 'Pais Presentes',
    description: 'Levar pais para eventos do clube ou da unidade.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 10,
    active: true
  },
  {
    id: 'q2-reunioes-pais',
    quarterNumber: 2,
    category: 'Família',
    name: 'Reuniões de Pais',
    description: '80% de presença nas reuniões convocadas.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 11,
    active: true
  },
  {
    id: 'q2-nos-amarras',
    quarterNumber: 2,
    category: 'Desenvolvimento do Desbravador',
    name: 'Nós e Amarras',
    description:
      'A cada reunião em que se pedir os nós, a unidade receberá 10 pontos se alcançar sucesso na execução dos nós. Pontuação total = quantidade de reuniões com êxito × 10.',
    points: 0,
    ruleType: 'RECURRING',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de reuniões com êxito em nós e amarras',
    pointsPerUnit: 10,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 12,
    active: true
  },
  {
    id: 'q2-socio-desbravador',
    quarterNumber: 2,
    category: 'Sócio Desbravador',
    name: 'Sócio Desbravador',
    description:
      'Meta de 04 sócios por unidade assíduos durante o ano. 100 pontos por cada sócio conquistado. O sócio pode ser: pais ou responsáveis, membros da igreja ou amigos externos.',
    points: 400,
    ruleType: 'QUANTITY_WITH_PENALTY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de sócios conquistados',
    pointsPerUnit: 100,
    maxQuantity: 4,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'MANUAL',
    penaltyValue: 100,
    penaltyDescription:
      'Perda de 100 pontos a cada sócio desistente ou 400 pontos caso não consiga nenhum sócio.',
    maxManualScore: null,
    displayOrder: 13,
    active: true
  },
  {
    id: 'q2-vendas-unidade',
    quarterNumber: 2,
    category: 'Finanças',
    name: 'Vendas na Unidade',
    description:
      'Cada unidade deverá ter pelo menos uma venda durante o ano, para comprar as coisas da unidade.',
    points: 200,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 200,
    penaltyDescription: 'Perda de 200 pontos caso não cumpra.',
    maxManualScore: null,
    displayOrder: 14,
    active: true
  }
];

export const rankingRequirementsQuarter3Seed: RankingRequirementSeed[] = [
  {
    id: 'q3-dia-fazer-bem',
    quarterNumber: 3,
    category: 'Impacto Social',
    name: 'Dia de Fazer o Bem',
    description: 'Realizar ações sociais como limpeza, doações ou ajuda comunitária.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 1,
    active: true
  },
  {
    id: 'q3-clube-no-lar',
    quarterNumber: 3,
    category: 'Impacto Social',
    name: 'Clube no Lar',
    description:
      'Realizar pelo menos uma vez na semana um culto na casa de um desbravador com meditação, louvor e oração.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 2,
    active: true
  },
  {
    id: 'q3-cesta-basica',
    quarterNumber: 3,
    category: 'Impacto Social',
    name: 'Cesta Básica',
    description: 'Arrecadar 01 cesta básica completa.',
    points: 100,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 3,
    active: true
  },
  {
    id: 'q3-semana-lenco',
    quarterNumber: 3,
    category: 'Impacto Social',
    name: 'Semana do Lenço',
    description: 'Uso do lenço durante toda a semana por todos da unidade.',
    points: 200,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 4,
    active: true
  },
  {
    id: 'q3-socio-trimestre',
    quarterNumber: 3,
    category: 'Engajamento e Sustentação',
    name: 'Sócio Desbravador (Trimestre)',
    description: 'Meta de 02 sócios no trimestre.',
    points: 100,
    ruleType: 'QUANTITY_WITH_PENALTY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de sócios no trimestre',
    pointsPerUnit: 50,
    maxQuantity: 2,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'FIXED',
    penaltyValue: 50,
    penaltyDescription: 'Perda de 50 pontos caso não consiga 02 sócios no trimestre.',
    maxManualScore: null,
    displayOrder: 5,
    active: true
  },
  {
    id: 'q3-barraca',
    quarterNumber: 3,
    category: 'Estrutura e Identidade',
    name: 'Barraca',
    description: '01 barraca para 07 pessoas como patrimônio da unidade.',
    points: 800,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 6,
    active: true
  },
  {
    id: 'q3-bandeirim',
    quarterNumber: 3,
    category: 'Estrutura e Identidade',
    name: 'Bandeirim',
    description: 'Bandeirim bordado com o nome da unidade.',
    points: 150,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 7,
    active: true
  },
  {
    id: 'q3-mastro',
    quarterNumber: 3,
    category: 'Estrutura e Identidade',
    name: 'Mastro',
    description:
      'Apresentar mastro organizado. O mastro mais criativo pode receber pontuação extra definida pela diretoria. Valor sugerido: +50 pontos (ajustável pela diretoria).',
    points: 150,
    ruleType: 'BOOLEAN_WITH_BONUS',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: true,
    bonusType: 'FIXED',
    bonusValue: 50,
    bonusDescription:
      'Pontuação extra para o mastro mais criativo. Valor sugerido: +50 pontos. Ajustar caso a diretoria defina outro valor.',
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 8,
    active: true
  },
  {
    id: 'q3-uniforme-atividades',
    quarterNumber: 3,
    category: 'Estrutura e Identidade',
    name: 'Uniforme de Atividades',
    description: 'Todos devem possuir camisa do clube. Penalidade de -100 pontos por desbravador sem camisa.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de desbravadores sem camisa do clube',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'MANUAL',
    penaltyValue: 100,
    penaltyDescription:
      'Perda de 100 pontos por desbravador sem camisa. Calcular: quantidade de desbravadores sem camisa × 100.',
    maxManualScore: null,
    displayOrder: 9,
    active: true
  },
  {
    id: 'q3-uniforme-oficial',
    quarterNumber: 3,
    category: 'Estrutura e Identidade',
    name: 'Uniforme Oficial',
    description: '100% da unidade com uniforme completo. Penalidade de -300 pontos por desbravador sem uniforme oficial completo.',
    points: 300,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de desbravadores sem uniforme oficial completo',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'MANUAL',
    penaltyValue: 300,
    penaltyDescription:
      'Perda de 300 pontos por desbravador sem uniforme oficial. Calcular: quantidade de desbravadores sem uniforme × 300.',
    maxManualScore: null,
    displayOrder: 10,
    active: true
  },
  {
    id: 'q3-camisa-mibes',
    quarterNumber: 3,
    category: 'Estrutura e Identidade',
    name: 'Camisa da MIBES',
    description: 'Todos devem possuir a camisa da MIBES. Penalidade de -50 pontos por desbravador sem camisa.',
    points: 100,
    ruleType: 'BOOLEAN_WITH_PENALTY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de desbravadores sem camisa da MIBES',
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'MANUAL',
    penaltyValue: 50,
    penaltyDescription:
      'Perda de 50 pontos por desbravador sem camisa da MIBES. Calcular: quantidade de desbravadores sem camisa × 50.',
    maxManualScore: null,
    displayOrder: 11,
    active: true
  },
  {
    id: 'q3-portal-clube',
    quarterNumber: 3,
    category: 'Estrutura e Identidade',
    name: 'Portal do Clube',
    description: 'Apresentar proposta de portal.',
    points: 150,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 12,
    active: true
  },
  {
    id: 'q3-batismo',
    quarterNumber: 3,
    category: 'Consagração Espiritual',
    name: 'Batismo',
    description: 'Alcançar 01 batismo no ano.',
    points: 800,
    ruleType: 'BOOLEAN',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 13,
    active: true
  },
  {
    id: 'q3-nos-amarras',
    quarterNumber: 3,
    category: 'Desenvolvimento do Desbravador',
    name: 'Nós e Amarras',
    description:
      'A cada reunião em que se pedir os nós, a unidade receberá 10 pontos se alcançar sucesso na execução dos nós. Pontuação total = quantidade de reuniões com êxito × 10.',
    points: 0,
    ruleType: 'RECURRING',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de reuniões com êxito em nós e amarras',
    pointsPerUnit: 10,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: null,
    displayOrder: 14,
    active: true
  },
  {
    id: 'q3-socio-desbravador',
    quarterNumber: 3,
    category: 'Sócio Desbravador',
    name: 'Sócio Desbravador',
    description:
      'Meta de 04 sócios por unidade assíduos durante o ano. 100 pontos por cada sócio conquistado. O sócio pode ser: pais ou responsáveis, membros da igreja ou amigos externos.',
    points: 400,
    ruleType: 'QUANTITY_WITH_PENALTY',
    requiresQuantity: true,
    quantityLabel: 'Quantidade de sócios conquistados',
    pointsPerUnit: 100,
    maxQuantity: 4,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: true,
    penaltyType: 'MANUAL',
    penaltyValue: 100,
    penaltyDescription:
      'Perda de 100 pontos a cada sócio desistente ou 400 pontos caso não consiga nenhum sócio.',
    maxManualScore: null,
    displayOrder: 15,
    active: true
  },
  {
    id: 'q3-oratorio',
    quarterNumber: 3,
    category: 'Concursos',
    name: 'Oratória',
    description:
      'Serão avaliados: coerência com o tema, fundamentação bíblica e desenvolvimento da oratória.',
    points: 350,
    ruleType: 'MANUAL_SCORE',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: 350,
    displayOrder: 16,
    active: true
  },
  {
    id: 'q3-musica',
    quarterNumber: 3,
    category: 'Concursos',
    name: 'Música',
    description:
      'Tema: "Sempre Desbravador". Letra e música devem ser originais e criadas pela unidade.',
    points: 350,
    ruleType: 'MANUAL_SCORE',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: 350,
    displayOrder: 17,
    active: true
  },
  {
    id: 'q3-poesia',
    quarterNumber: 3,
    category: 'Concursos',
    name: 'Poesia',
    description:
      'Tema: "Sempre Desbravador". Duração até 03 minutos. Avaliação: conteúdo, criatividade e apresentação.',
    points: 250,
    ruleType: 'MANUAL_SCORE',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: 250,
    displayOrder: 18,
    active: true
  },
  {
    id: 'q3-desafio-nos-amarras',
    quarterNumber: 3,
    category: 'Concursos',
    name: 'Desafio Nós e Amarras',
    description:
      'A unidade que realizar no menor tempo todos os nós da classe de amigo.',
    points: 300,
    ruleType: 'MANUAL_SCORE',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: 300,
    displayOrder: 19,
    active: true
  },
  {
    id: 'q3-ordem-unida',
    quarterNumber: 3,
    category: 'Concurso de Ordem Unida',
    name: 'Ordem Unida',
    description:
      'Avaliar disciplina, organização, postura e domínio dos comandos. Participação mínima de 80% da unidade. Tempo: 5 a 7 minutos (penalidade de -1 ponto a cada 10 segundos excedidos). Critérios: comandos parados (20), comandos em movimento (20), postura (10), alinhamento básico (10), comando (15), comandos avançados (15), alinhamento avançado (10), brado (15). Extras: até +10 pontos (apito, gestos, corneta).',
    points: 115,
    ruleType: 'MANUAL_SCORE',
    requiresQuantity: false,
    quantityLabel: null,
    pointsPerUnit: null,
    maxQuantity: null,
    allowBonus: false,
    bonusType: null,
    bonusValue: null,
    bonusDescription: null,
    allowPenalty: false,
    penaltyType: null,
    penaltyValue: null,
    penaltyDescription: null,
    maxManualScore: 115,
    displayOrder: 20,
    active: true
  }
];

export const DEFAULT_RANKING_REQUIREMENT_SEEDS: RankingRequirementSeed[] = [
  ...rankingRequirementsQuarter1Seed,
  ...rankingRequirementsQuarter2Seed,
  ...rankingRequirementsQuarter3Seed,
];

export const buildDefaultRankingRequirements = (year: number): RankingRequirement[] => {
  const quarters = buildDefaultRankingQuarters(year);
  const quarterMap = new Map(quarters.map(quarter => [quarter.number, quarter.id]));

  return DEFAULT_RANKING_REQUIREMENT_SEEDS.map(seed => ({
    ...seed,
    quarterId: quarterMap.get(seed.quarterNumber) || '',
    active: seed.active,
    origem: 'PADRAO' as const
  }));
};
